#!/usr/bin/bash

usage() { 
  echo 
  echo "Usage: $0 [ -b ] [ -s ]"; 
  echo 
  echo "Params:"; 
  echo "  -b - Buy"; 
  echo "  -s - Sell"; 
  echo "Examples:"; 
  echo "  $0 -bs"; 
  echo "  $0 -b"; 
  echo "  $0 -s"; 
  exit 1; 
  
  }
while getopts "bs" arg; do
  case $arg in
    b)
      curl -s https://www.rico.ge/en | grep -Eo "[0-9]\.[0-9]{4}" | awk 'NR==1{print "Buy GEL "$1}'
      ;;
    s)
      curl -s https://www.rico.ge/en | grep -Eo "[0-9]\.[0-9]{4}" | awk 'NR==2{print "Sell GEL "$1}'
      ;;
  esac
done

if [ $# -eq 0 ]; then
    usage
    exit 1
fi
